name: CI/CD pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Maven Package
      run: mvn -B package --file pom.xml

    - name: Bump version and commit
      id: bump_version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.eyallevi }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.eyallevi }}/simple-java-maven-app:${{ steps.bump_version.outputs.new_tag }}
