name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ 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 }}

      - name: Configure git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Increase the patch version
        run: |
          mvn versions:set -DnewVersion=1.0.${{ github.run_number }} -DgenerateBackupPoms=false
          git commit -am "Bump version to 1.0.${{ github.run_number }}"
          git push

      - name: Build Docker image
        run: |
          docker build -t my-app:1.0.${{ github.run_number }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag my-app:1.0.${{ github.run_number }} ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:1.0.${{ github.run_number }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:1.0.${{ github.run_number }}
